// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjanrugmhefpgrbrazou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqYW5ydWdtaGVmcGdyYnJhem91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NDA4MTAsImV4cCI6MjA2OTIxNjgxMH0.WOmxV7tjgyFSURJd_qQTFTsjlBR2uC4mRBvIjU1DCyU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});